from __future__ import annotations

from typing import Protocol

from tlvflow.domain.rides import Ride
from tlvflow.domain.users import User


class UsersRepositoryProtocol(Protocol):
    def get_by_id(self, user_id: str) -> User | None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def add(self, user: User) -> None: ...


class ActiveUsersRepositoryProtocol(Protocol):
    def get_ride_id(self, user_id: str) -> str | None: ...

    def is_active(self, user_id: str) -> bool: ...

    def set_active(self, user_id: str, ride_id: str) -> None: ...

    def clear(self, user_id: str) -> None: ...

    def get_active_user_ids(self) -> list[str]: ...


class RidesRepositoryProtocol(Protocol):
    def get_by_id(self, ride_id: str) -> Ride | None: ...

    def get_by_user_id(self, user_id: str) -> list[Ride]: ...

    def add(self, ride: Ride) -> None: ...
